#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = -ldl -lglfw -lassimp
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/learnOpenGL

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/learnOpenGL

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/shader.o $(OBJDIR_DEBUG)/src/model.o $(OBJDIR_DEBUG)/src/mesh.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/glad.o $(OBJDIR_DEBUG)/src/entity.o $(OBJDIR_DEBUG)/src/collision.o $(OBJDIR_DEBUG)/src/camera.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/shader.o $(OBJDIR_RELEASE)/src/model.o $(OBJDIR_RELEASE)/src/mesh.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/glad.o $(OBJDIR_RELEASE)/src/entity.o $(OBJDIR_RELEASE)/src/collision.o $(OBJDIR_RELEASE)/src/camera.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/shader.o: src/shader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/shader.cpp -o $(OBJDIR_DEBUG)/src/shader.o

$(OBJDIR_DEBUG)/src/model.o: src/model.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/model.cpp -o $(OBJDIR_DEBUG)/src/model.o

$(OBJDIR_DEBUG)/src/mesh.o: src/mesh.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/mesh.cpp -o $(OBJDIR_DEBUG)/src/mesh.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/glad.o: src/glad.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/glad.c -o $(OBJDIR_DEBUG)/src/glad.o

$(OBJDIR_DEBUG)/src/entity.o: src/entity.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entity.cpp -o $(OBJDIR_DEBUG)/src/entity.o

$(OBJDIR_DEBUG)/src/collision.o: src/collision.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/collision.cpp -o $(OBJDIR_DEBUG)/src/collision.o

$(OBJDIR_DEBUG)/src/camera.o: src/camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/camera.cpp -o $(OBJDIR_DEBUG)/src/camera.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/shader.o: src/shader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/shader.cpp -o $(OBJDIR_RELEASE)/src/shader.o

$(OBJDIR_RELEASE)/src/model.o: src/model.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/model.cpp -o $(OBJDIR_RELEASE)/src/model.o

$(OBJDIR_RELEASE)/src/mesh.o: src/mesh.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/mesh.cpp -o $(OBJDIR_RELEASE)/src/mesh.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/glad.o: src/glad.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/glad.c -o $(OBJDIR_RELEASE)/src/glad.o

$(OBJDIR_RELEASE)/src/entity.o: src/entity.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entity.cpp -o $(OBJDIR_RELEASE)/src/entity.o

$(OBJDIR_RELEASE)/src/collision.o: src/collision.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/collision.cpp -o $(OBJDIR_RELEASE)/src/collision.o

$(OBJDIR_RELEASE)/src/camera.o: src/camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/camera.cpp -o $(OBJDIR_RELEASE)/src/camera.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

